apiVersion: v1
kind: Secret
metadata:
  name: quick-serve-api-secret
  labels:
    name: quick-serve-api-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcXVpY2stc2VydmUtZGIuY2xoOGRnbXVmcGJsLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3F1aWNrc2VydmU=
