name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker buildx build \
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/quick-serve-api:latest \
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/quick-serve-api:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/quick-serve-api:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/quick-serve-api:${{ github.sha }}
