name: Build Docker Image and Java Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build \
            --tag quick-serve-api:latest .  # Certifique-se de que o nome da imagem está correto

      - name: Test Docker image
        run: |
          docker run --rm quick-serve-api:latest java -version  # Executa a imagem construída
