name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/quick-serve-api:latest \
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/quick-serve-api:${{ github.sha }} \
            --push .  # Adiciona --push para enviar a imagem durante a build
